#!/usr/bin/env python3
"""
Build complete PDF summary of QRI project.
Combines all reports, analysis, and architecture specs into single PDF.
"""

import subprocess
import os
from pathlib import Path

def build_pdf():
    repo_root = Path(__file__).parent.parent
    
    # Read markdown files
    final_report = (repo_root / "FINAL_REPORT_NARG_PTYCH_SNR_2026-04-24.md").read_text()
    econ_perf = (repo_root / "ECONOMICS_AND_PERFORMANCE_2026-04-24.md").read_text()
    snr_upgrade = (repo_root / "SNR_UPGRADE_ELECTRONICS_2026-04-24.md").read_text()
    arch = (repo_root / "architecture.md").read_text()[:6000]
    
    # Build master markdown
    master = f"""---
title: Quantum Resonator Inference
subtitle: Complete Project Summary
author: Jason Edelman
date: 2026-04-24
geometry: margin=0.75in
fontsize: 11pt
linestretch: 1.2
toc: true
toc-depth: 3
---

# Quantum Resonator Inference: Complete Project Summary

**Date:** 2026-04-24  
**Status:** Architecture LOCKED. Electronics upgrade specified. Production-ready.

---

## Part 1: Executive Summary & Recommendations

{final_report}

---

## Part 2: Economics & Performance Analysis

{econ_perf}

---

## Part 3: Electronics Upgrade Specifications

{snr_upgrade}

---

## Appendix A: Architecture Specification (excerpt)

{arch}

[Full architecture: `architecture.md`]

---

## Appendix B: Key Performance Metrics

| Metric | Baseline | Path A | Path B ⭐ | Path C |
|:---|:---:|:---:|:---:|:---:|
| Latency gain | — | 16× | **128×** | **128×** |
| SNR (dB) | 40 | 40 | 48 | 48 |
| Parameters (M) | 1.23 | 1.23 | 1.23 | 2.46 |
| Cost | $0 | $0 | $5k | $6k |
| Timeline | 0 | 2wk | 6wk | 8wk |

---

## Appendix C: Economics Summary

**QRI vs. Hyperscale (5-year TCO):**
- Capital: 138× cheaper ($1.0B vs $143.4B)
- Annual OpEx: 422× cheaper ($73M vs $30.8B)
- Total TCO: 212× cheaper ($1.4B vs $297.4B)
- Payback: 0.4 months
- Carbon: 44× lower

---

## Appendix D: Files & Resources

**Reports (Markdown):**
- `FINAL_REPORT_NARG_PTYCH_SNR_2026-04-24.md` — Analysis & decision tree
- `ECONOMICS_AND_PERFORMANCE_2026-04-24.md` — Path comparison & ROI
- `SNR_UPGRADE_ELECTRONICS_2026-04-24.md` — Phase specifications
- `NARG_PTYCH_CROSSCHECK_2026-04-24.md` — Feasibility details

**Analysis Scripts:**
- `analyze/arch_crosscheck.py` — Architecture consistency checks
- `analyze/economic_analysis.py` — 5-year TCO comparison
- `analyze/performance_update.py` — Scenario comparison tool

**Repository:**
https://github.com/jedelman/quantum-resonator-inference

---

Generated by `make pdf` on {Path(__file__).parent.parent.name}
"""
    
    # Write master markdown
    master_file = repo_root / "QRI_Complete_Summary_2026-04-24.md"
    master_file.write_text(master)
    print(f"✓ Master markdown: {master_file.name}")
    
    # Try pandoc -> PDF
    try:
        subprocess.run([
            "pandoc",
            str(master_file),
            "-o", str(repo_root / "QRI_Complete_Summary_2026-04-24.pdf"),
            "--pdf-engine=xelatex",
            "-V", "geometry:margin=0.75in",
            "-V", "fontsize=11pt",
            "-V", "linestretch=1.2",
        ], check=True, capture_output=True)
        print(f"✓ PDF generated: QRI_Complete_Summary_2026-04-24.pdf")
        return True
    except FileNotFoundError:
        print("⚠ pandoc not found, generating HTML...")
    except subprocess.CalledProcessError as e:
        print(f"⚠ pandoc error: {e.stderr.decode()}")
    
    # Fallback: HTML
    try:
        subprocess.run([
            "pandoc",
            str(master_file),
            "-o", str(repo_root / "QRI_Complete_Summary_2026-04-24.html"),
            "-s", "--toc", "--toc-depth=3",
            "-c", "style.css"
        ], check=False)
        print(f"✓ HTML generated: QRI_Complete_Summary_2026-04-24.html")
    except:
        print("✓ Master markdown saved (install pandoc for PDF/HTML)")
    
    return False

if __name__ == "__main__":
    build_pdf()
