#!/usr/bin/env python3
"""
build_pdf_report.py
Assembles and renders the QRI system document as PDF and HTML.
Sources: architecture.md, properties.toml, parameters.toml, analyze/ outputs.
Replaces hardcoded 2026-04-24 file references.
"""

import subprocess
import sys
import tomllib
from pathlib import Path
from datetime import date

ROOT = Path(__file__).parent.parent
TODAY = date.today().isoformat()


def run_crosscheck() -> str:
    result = subprocess.run(
        [sys.executable, str(ROOT / "analyze" / "arch_crosscheck.py"), "--output", "table"],
        capture_output=True, text=True, cwd=str(ROOT)
    )
    return result.stdout.strip()


def run_analysis(script: str, *args) -> str:
    result = subprocess.run(
        [sys.executable, str(ROOT / "analyze" / script), *args],
        capture_output=True, text=True, cwd=str(ROOT)
    )
    return result.stdout.strip()


def load_toml(path: Path) -> dict:
    with open(path, "rb") as f:
        return tomllib.load(f)


def render_properties(props: dict) -> str:
    lines = []
    for material, values in props.items():
        if not isinstance(values, dict):
            continue
        lines.append(f"### `{material}`")
        if "description" in values:
            lines.append(f"*{values['description']}*\n")
        for k, v in values.items():
            if k not in ("description", "cite", "note"):
                lines.append(f"- **{k}**: {v}")
        if "note" in values:
            lines.append(f"\n> Note: {values['note']}")
        lines.append(f"\n> Cite: {values.get('cite', 'MISSING')}\n")
    return "\n".join(lines)


def render_parameters(params: dict) -> str:
    lines = []
    for section, values in params.items():
        if not isinstance(values, dict):
            continue
        lines.append(f"### `{section}`\n")
        lines.append("| Parameter | Value |")
        lines.append("|:---|:---|")
        for k, v in values.items():
            if not str(k).startswith("#"):
                lines.append(f"| {k} | `{v}` |")
        lines.append("")
    return "\n".join(lines)


def assemble() -> str:
    arch = (ROOT / "architecture.md").read_text()
    tasks = (ROOT / "TASKS.md").read_text()
    props = load_toml(ROOT / "properties.toml")
    params = load_toml(ROOT / "parameters.toml")

    crosscheck = run_crosscheck()
    econ = run_analysis("economic_analysis.py", "--years", "5", "--output", "table")
    perf = run_analysis("performance_update.py", "--output", "table")

    doc = f"""---
title: "Optical Resonator Inference"
subtitle: "System Design Document"
author: "Jason Edelman"
date: "{TODAY}"
geometry: "margin=0.85in"
fontsize: 10pt
linestretch: 1.25
toc: true
toc-depth: 3
numbersections: true
---

\\newpage

# Optical Resonator Inference: System Design Document

**Generated:** {TODAY}
**Status:** ARCH-1 through ARCH-17 LOCKED. Experimental validation phase.
**Repo:** https://github.com/jedelman/quantum-resonator-inference

---

{arch}

\\newpage

# Architecture Cross-Check

All architecture decisions validated for mutual consistency by `analyze/arch_crosscheck.py`.

```
{crosscheck}
```

\\newpage

# Experimental Validation Tasks

{tasks}

\\newpage

# Material Properties

{render_properties(props)}

\\newpage

# Design Parameters

{render_parameters(params)}

\\newpage

# Economic Analysis (5-Year TCO)

```
{econ}
```

\\newpage

# Performance Scenarios

```
{perf}
```

---

*End of document. Generated by `analyze/build_pdf_report.py` on {TODAY}.*
"""
    return doc


def build():
    print("Assembling document...")
    doc = assemble()

    renders = ROOT / "renders"
    renders.mkdir(exist_ok=True)
    md_out = renders / f"QRI_System_Doc_{TODAY}.md"
    md_out.write_text(doc)
    print(f"Markdown: {md_out.name}")

    pdf_out = renders / f"QRI_System_Doc_{TODAY}.pdf"
    try:
        result = subprocess.run(
            [
                "pandoc", str(md_out),
                "-o", str(pdf_out),
                "--pdf-engine=pdflatex",
                "--highlight-style=tango",
                "-V", "colorlinks=true",
                "-V", "linkcolor=blue",
            ],
            capture_output=True, text=True
        )
        if result.returncode == 0:
            print(f"PDF:      {pdf_out.name}")
            return str(pdf_out)
        else:
            print(f"xelatex error: {result.stderr[:300]}")
    except FileNotFoundError:
        print("pandoc not found")

    html_out = renders / f"QRI_System_Doc_{TODAY}.html"
    try:
        subprocess.run(
            [
                "pandoc", str(md_out),
                "-o", str(html_out),
                "-s", "--toc", "--toc-depth=3",
                "--highlight-style=tango",
            ],
            check=True, capture_output=True
        )
        print(f"HTML:     {html_out.name}")
        return str(html_out)
    except Exception as e:
        print(f"HTML fallback failed: {e}")
        return str(md_out)


if __name__ == "__main__":
    output = build()
    print(f"Output: {output}")
# Note: primary PDF via pandoc+latex; fallback is wkhtmltopdf from HTML.
# Run: wkhtmltopdf renders/QRI_System_Doc_DATE.html renders/QRI_System_Doc_DATE.pdf
